/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package project_qlsinhvien;

/**
 *
 * @author Dell Precision 7550
 */
public class fmCuaSoChinh extends javax.swing.JFrame {

    public static boolean isTrangThaiDangNhap = false;
    
    //Lưu thông tin tên đăng nhập và UserId
    public static String userName = "";    
    public static int userId = 0;
    
    /**
     * Creates new form fmCuaSoChinh
     */
    public fmCuaSoChinh() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        lblTrangThai = new javax.swing.JLabel();
        lblVaiTro = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuHeThong = new javax.swing.JMenu();
        jMenuItemUser = new javax.swing.JMenuItem();
        jMenuItemDangNhap = new javax.swing.JMenuItem();
        jMenuItemDangXuat = new javax.swing.JMenuItem();
        jMenuItemThoat = new javax.swing.JMenuItem();
        jMenuNghiepVu = new javax.swing.JMenu();
        jMenuItemSV = new javax.swing.JMenuItem();
        jMenuItemNhapDiemThi = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItemTraCuuDiemThi = new javax.swing.JMenuItem();
        jMenuDanhMuc = new javax.swing.JMenu();
        jMenuItemPH = new javax.swing.JMenuItem();
        jMenuItemMH = new javax.swing.JMenuItem();
        jMenuItemKhoa = new javax.swing.JMenuItem();
        jMenuBaoCao = new javax.swing.JMenu();
        jMenuTroGiup = new javax.swing.JMenu();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Hệ thống quản lý sinh viên");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        lblTrangThai.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTrangThai.setText("UserDangNhap");

        lblVaiTro.setText("VaiTroDangNhap");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(763, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblVaiTro)
                    .addComponent(lblTrangThai, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(lblTrangThai)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblVaiTro)
                .addGap(21, 21, 21))
        );

        jMenuHeThong.setText("Hệ thống");

        jMenuItemUser.setText("Quản lý người dùng");
        jMenuItemUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemUserActionPerformed(evt);
            }
        });
        jMenuHeThong.add(jMenuItemUser);

        jMenuItemDangNhap.setText("Đăng nhập");
        jMenuItemDangNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemDangNhapActionPerformed(evt);
            }
        });
        jMenuHeThong.add(jMenuItemDangNhap);

        jMenuItemDangXuat.setText("Đăng xuất");
        jMenuItemDangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemDangXuatActionPerformed(evt);
            }
        });
        jMenuHeThong.add(jMenuItemDangXuat);

        jMenuItemThoat.setText("Đóng chương trình");
        jMenuItemThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemThoatActionPerformed(evt);
            }
        });
        jMenuHeThong.add(jMenuItemThoat);

        jMenuBar1.add(jMenuHeThong);

        jMenuNghiepVu.setText("Nghiệp vụ");

        jMenuItemSV.setText("Quản lý sinh viên");
        jMenuItemSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSVActionPerformed(evt);
            }
        });
        jMenuNghiepVu.add(jMenuItemSV);

        jMenuItemNhapDiemThi.setText("Nhập điểm thi");
        jMenuItemNhapDiemThi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemNhapDiemThiActionPerformed(evt);
            }
        });
        jMenuNghiepVu.add(jMenuItemNhapDiemThi);
        jMenuNghiepVu.add(jSeparator1);

        jMenuItemTraCuuDiemThi.setText("Tra cứu điểm thi");
        jMenuNghiepVu.add(jMenuItemTraCuuDiemThi);

        jMenuBar1.add(jMenuNghiepVu);

        jMenuDanhMuc.setText("Danh mục");

        jMenuItemPH.setText("Quản lý phòng học");
        jMenuItemPH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPHActionPerformed(evt);
            }
        });
        jMenuDanhMuc.add(jMenuItemPH);

        jMenuItemMH.setText("Quản lý môn học");
        jMenuItemMH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemMHActionPerformed(evt);
            }
        });
        jMenuDanhMuc.add(jMenuItemMH);

        jMenuItemKhoa.setText("Quản lý khoa");
        jMenuItemKhoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemKhoaActionPerformed(evt);
            }
        });
        jMenuDanhMuc.add(jMenuItemKhoa);

        jMenuBar1.add(jMenuDanhMuc);

        jMenuBaoCao.setText("Báo cáo");
        jMenuBar1.add(jMenuBaoCao);

        jMenuTroGiup.setText("Trợ giúp");
        jMenuBar1.add(jMenuTroGiup);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 471, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemUserActionPerformed
        //Gọi form quản lý người dùng
       fmDSNguoiDung fmUser = new fmDSNguoiDung();
       
       fmUser.setVisible(true);
    }//GEN-LAST:event_jMenuItemUserActionPerformed

    private void jMenuItemSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSVActionPerformed
        //HIển thị form danh sách sinh viên
        fmDanhSachSV fmSinhVien = new fmDanhSachSV();
        
        fmSinhVien.setVisible(true);
    }//GEN-LAST:event_jMenuItemSVActionPerformed

    private void jMenuItemDangNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDangNhapActionPerformed
        //Gọi hàm đăng nhập hệ thống
        dangNhapHeThong();
    }//GEN-LAST:event_jMenuItemDangNhapActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        //Gọi hàm kiểm tra quyền sử dụng 
        kiemTraQuyenSuDung(isTrangThaiDangNhap);
    }//GEN-LAST:event_formWindowOpened

    private void jMenuItemDangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDangXuatActionPerformed
        //Set trạng thái hàm kiểm tra quyền sử dụng sau khi đăng xuất
        isTrangThaiDangNhap = false;
        
        //Reset trạng thái hiển thị khi đăng xuất
        userName = "";
        userId = 0;
        
        //Gọi hàm đăng nhập hệ thống
        dangNhapHeThong();
    }//GEN-LAST:event_jMenuItemDangXuatActionPerformed

    private void jMenuItemThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemThoatActionPerformed
        //Thoát chương trình
        System.exit(0);
    }//GEN-LAST:event_jMenuItemThoatActionPerformed

    private void jMenuItemNhapDiemThiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemNhapDiemThiActionPerformed
        //Gọi form nhập/tra cứu điểm thi
        fmDSDiemThi fmDiemThi = new fmDSDiemThi();
        
        fmDiemThi.setVisible(true);
    }//GEN-LAST:event_jMenuItemNhapDiemThiActionPerformed

    private void jMenuItemPHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPHActionPerformed
        //Gọi form quản lý phòng học
        fmDanhSachPhongHoc fmPH = new fmDanhSachPhongHoc();
        
        fmPH.setVisible(true);
    }//GEN-LAST:event_jMenuItemPHActionPerformed

    private void jMenuItemMHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemMHActionPerformed
        //Gọi form quản lý môn học
        fmDanhSachMonHoc fmMH = new fmDanhSachMonHoc();
        
        fmMH.setVisible(true);
    }//GEN-LAST:event_jMenuItemMHActionPerformed

    private void jMenuItemKhoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemKhoaActionPerformed
        //Gọi form quản lý khoa
        fmDanhSachKhoa fmKhoa = new fmDanhSachKhoa();
        
        fmKhoa.setVisible(true);
    }//GEN-LAST:event_jMenuItemKhoaActionPerformed
    
    private void dangNhapHeThong()
    {
        //Set trạng thái hàm kiểm tra quyền sử dụng trước khi đăng nhập được vào hệ thống
        kiemTraQuyenSuDung(false);
        
        //Gọi form đăng nhập
        fmDangNhap fmLogin = new fmDangNhap(); 
        fmLogin.setVisible(true);       
    }
    
    /**
     * Hàm kiểm tra và xử lý quyền sử dụng chức năng của phần mềm khi đăng nhập thành công hay không
     * @param isQuyen 
     */
    private void kiemTraQuyenSuDung(boolean isQuyen)
    {
        //Quyền sử dụng chức năng của phần mềm khi đăng nhập thành công hay không
        jMenuItemDangNhap.setVisible(!isQuyen);
        jMenuItemDangXuat.setVisible(isQuyen);
        
        //Thực hiện phân quyền
        if(isQuyen)
        {
            if(!userName.isEmpty() && userId != 0)//Nếu đăng nhập thành công
            {
                //Lấy vai trò người dùng để phân quyền
                NguoiDungBus nguoiDungBus = new NguoiDungBus();
                NguoiDung objUser = nguoiDungBus.layThongTinDangNhap(userName); 
                //Quản lý
                if(objUser.getTenVaiTro().equals("Quản lý"))
                {
                    jMenuItemUser.setVisible(isQuyen);
                    jMenuNghiepVu.setEnabled(isQuyen);
                    jMenuDanhMuc.setEnabled(isQuyen);
                    jMenuBaoCao.setEnabled(isQuyen);  
                }
                else//Nhân viên
                {
                    jMenuItemUser.setVisible(!isQuyen);
                    jMenuNghiepVu.setEnabled(isQuyen);
                    jMenuDanhMuc.setEnabled(!isQuyen);
                    jMenuBaoCao.setEnabled(isQuyen);            
                } 
                lblTrangThai.setText("Tài khoản: " + userName);
                lblVaiTro.setText("Chức năng: " + objUser.getTenVaiTro());
            }            
        }
        else//Nếu chưa đăng nhập
        {
            jMenuItemUser.setVisible(isQuyen);
            jMenuNghiepVu.setEnabled(isQuyen);
            jMenuDanhMuc.setEnabled(isQuyen);
            jMenuBaoCao.setEnabled(isQuyen); 
            lblTrangThai.setText("Chưa đăng nhập");
            lblVaiTro.setText("");            
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fmCuaSoChinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fmCuaSoChinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fmCuaSoChinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fmCuaSoChinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fmCuaSoChinh().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenuBaoCao;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuDanhMuc;
    private javax.swing.JMenu jMenuHeThong;
    private javax.swing.JMenuItem jMenuItemDangNhap;
    private javax.swing.JMenuItem jMenuItemDangXuat;
    private javax.swing.JMenuItem jMenuItemKhoa;
    private javax.swing.JMenuItem jMenuItemMH;
    private javax.swing.JMenuItem jMenuItemNhapDiemThi;
    private javax.swing.JMenuItem jMenuItemPH;
    private javax.swing.JMenuItem jMenuItemSV;
    private javax.swing.JMenuItem jMenuItemThoat;
    private javax.swing.JMenuItem jMenuItemTraCuuDiemThi;
    private javax.swing.JMenuItem jMenuItemUser;
    private javax.swing.JMenu jMenuNghiepVu;
    private javax.swing.JMenu jMenuTroGiup;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JLabel lblTrangThai;
    private javax.swing.JLabel lblVaiTro;
    // End of variables declaration//GEN-END:variables
}
