/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package namcat_baitaplaptrinhdesktopjv01part3;

import java.text.DecimalFormat;
import javax.swing.JOptionPane;
import java.text.NumberFormat;

/**
 *
 * @author Dell Precision 7550
 */
public class fmTienDiAn extends javax.swing.JFrame {

    /**
     * Creates new form fmTienDiAn
     */
    public fmTienDiAn() {
	initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtTienAn = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtSoNguoi = new javax.swing.JTextField();
        txtTienThue1 = new javax.swing.JTextField();
        txtTienBo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtTienAnTruocThue = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtTienThue2 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtTienAnSauThue = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        btnTinhToan = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Bảng tính tiền ăn", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

        jLabel1.setText("Tổng số tiền ăn cần phải trả");

        jLabel2.setText("Số người đi ăn");

        jLabel3.setText("Tiền thuế (% VAT)");

        jLabel4.setText("Tiền bo");

        jLabel5.setText("VNĐ");

        txtSoNguoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSoNguoiActionPerformed(evt);
            }
        });

        txtTienThue1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTienThue1ActionPerformed(evt);
            }
        });

        jLabel6.setText("VNĐ");

        jLabel7.setText("%");

        jLabel8.setText("người");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Tổng tiền sau VAT"));

        jLabel9.setText("Tổng tiền trước VAT");

        jLabel11.setText("Tiền VAT");

        jLabel12.setText("VNĐ");

        jLabel13.setText("VNĐ");

        jLabel14.setText("Tổng tiền sau VAT");

        jLabel15.setText("VNĐ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel11)
                    .addComponent(jLabel14))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtTienAnTruocThue, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                    .addComponent(txtTienThue2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtTienAnSauThue))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(jLabel15))
                .addContainerGap(98, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtTienAnTruocThue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel13)
                        .addComponent(txtTienThue2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txtTienAnSauThue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        btnTinhToan.setText("Tính toán");
        btnTinhToan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTinhToanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtTienBo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                            .addComponent(txtTienAn, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTienThue1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSoNguoi))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                                .addComponent(btnTinhToan))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(19, 19, 19))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtTienAn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(btnTinhToan))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtSoNguoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtTienThue1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtTienBo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTienThue1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTienThue1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTienThue1ActionPerformed

    private void txtSoNguoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSoNguoiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSoNguoiActionPerformed

    private void btnTinhToanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTinhToanActionPerformed
        // TODO add your handling code here:
	//Declare variables
	String strTienAn = "", strSoNguoi = "", strTienThue1 = "", strTienBo = "", strTienAnTruocThue = "", strTienThue2 = "", strTienAnSauThue = "";
	long tienAn = 0, soNguoi = 0, tienThue1 = 0, tienBo = 0, tienAnTruocThue = 0, tienThue2 = 0, tienAnSauThue = 0;
	
	//Take user information entered on the interface
	strTienAn = txtTienAn.getText();
	strSoNguoi = txtSoNguoi.getText();
	strTienThue1 = txtTienThue1.getText();
	strTienThue2 = txtTienThue2.getText();
	strTienBo = txtTienBo.getText();
	strTienAnSauThue = txtTienAnTruocThue.getText();
	strTienAnSauThue = txtTienAnSauThue.getText();
	
	//Convert String to Int
	//Nhập tiền ăn
	if(strTienAn.length() == 0)
	{
	    JOptionPane.showMessageDialog(rootPane, "Bạn phải nhập tổng số tiền ăn cần phải trả");
	    txtTienAn.requestFocus();
	    return;
	}
	try
	{
	    tienAn = Long.parseLong(strTienAn);
	}
	catch(NumberFormatException ex)
	{
	    System.err.println("Tổng tiền ăn cần phải trả chỉ bao gồm các kí tự số. Chi tiết lỗi" + ex.getMessage());
	    JOptionPane.showMessageDialog(rootPane, "Tổng tiền ăn cần phải trả chỉ bao gồm các kí tự số");
	    txtTienAn.requestFocus();
	    return;
	}
	
	//Nhập số người đi ăn
	if(strSoNguoi.length() == 0)
	{
	    JOptionPane.showMessageDialog(rootPane, "Bạn phải nhập số người đi ăn");
	    txtSoNguoi.requestFocus();
	    return;
	}
	try
	{
	    soNguoi = Long.parseLong(strSoNguoi);
	}
	catch(NumberFormatException ex)
	{
	    System.err.println("Số người đi ăn chỉ bao gồm các kí tự số. Chi tiết lỗi" + ex.getMessage());
	    JOptionPane.showMessageDialog(rootPane, "Số người đi ăn chỉ bao gồm các kí tự số");
	    txtSoNguoi.requestFocus();
	    return;
	}
	
	//Nhập % thuế
	if(strTienThue1.length() == 0)
	{
	    JOptionPane.showMessageDialog(rootPane, "Bạn phải nhập % thuế");
	    txtTienThue1.requestFocus();
	    return;
	}
	try
	{
	    tienThue1 = Long.parseLong(strTienThue1);
	}
	catch(NumberFormatException ex)
	{
	    System.err.println("Phần trăm thuế (%) chỉ bao gồm các kí tự số. Chi tiết lỗi" + ex.getMessage());
	    JOptionPane.showMessageDialog(rootPane, "Phần trăm thuế (%) chỉ bao gồm các kí tự số");
	    txtTienThue1.requestFocus();
	    return;
	}	

	//Tiền bo
	if (strTienBo.length() != 0) {
	    try {
		tienBo = Long.parseLong(strTienBo);
	    } catch (NumberFormatException ex) {
		System.err.println("Tiền bo chỉ bao gồm các kí tự số. Chi tiết lỗi" + ex.getMessage());
		JOptionPane.showMessageDialog(rootPane, "Tiền bo chỉ bao gồm các kí tự số");
		txtTienBo.requestFocus();
		return;
	    }
	}

	//Computational processing
	tienAnTruocThue = tienAn;
	tienThue2 = (tienAn*tienThue1)/100;
	tienAnSauThue = tienAn + tienThue2 + tienBo;
	
	//Convert to Currency Unit
	NumberFormat currentLocale = NumberFormat.getInstance();
	String str1 = currentLocale.format(tienAnTruocThue);
	String str2 = currentLocale.format(tienAnSauThue);
	String str3 = currentLocale.format(tienThue2);
	
	//Print results
	txtTienAnTruocThue.setText(str1);
	txtTienThue2.setText(str3);
	txtTienAnSauThue.setText(str2);
	
    }//GEN-LAST:event_btnTinhToanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
	/* Set the Nimbus look and feel */
	//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
	/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
	 */
	try {
	    for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
		if ("Nimbus".equals(info.getName())) {
		    javax.swing.UIManager.setLookAndFeel(info.getClassName());
		    break;
		}
	    }
	} catch (ClassNotFoundException ex) {
	    java.util.logging.Logger.getLogger(fmTienDiAn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (InstantiationException ex) {
	    java.util.logging.Logger.getLogger(fmTienDiAn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (IllegalAccessException ex) {
	    java.util.logging.Logger.getLogger(fmTienDiAn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (javax.swing.UnsupportedLookAndFeelException ex) {
	    java.util.logging.Logger.getLogger(fmTienDiAn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	}
	//</editor-fold>

	/* Create and display the form */
	java.awt.EventQueue.invokeLater(new Runnable() {
	    public void run() {
		new fmTienDiAn().setVisible(true);
	    }
	});
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTinhToan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtSoNguoi;
    private javax.swing.JTextField txtTienAn;
    private javax.swing.JTextField txtTienAnSauThue;
    private javax.swing.JTextField txtTienAnTruocThue;
    private javax.swing.JTextField txtTienBo;
    private javax.swing.JTextField txtTienThue1;
    private javax.swing.JTextField txtTienThue2;
    // End of variables declaration//GEN-END:variables
}
