/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package project_qlsinhvien;

import java.text.SimpleDateFormat;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Dell Precision 7550
 */
public class fmDanhSachSV extends javax.swing.JFrame {

    public String getMaKhoa() {
        return maKhoa;
    }

    public void setMaKhoa(String maKhoa) {
        this.maKhoa = maKhoa;
    }

    private String maKhoa = "";
    
    /**
     * Creates new form fmDanhSachSV
     */
    public fmDanhSachSV() {
	initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField6 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableSinhVien = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtTuKhoa = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cboChuyenKhoa = new javax.swing.JComboBox<>();
        btnTimKiem = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnLuu = new javax.swing.JButton();
        btnDong = new javax.swing.JButton();
        btnThemMoi = new javax.swing.JButton();

        jTextField6.setText("jTextField6");

        setTitle("Quản lý thông tin sinh viên");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Danh sách sinh viên", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N
        jScrollPane1.setPreferredSize(new java.awt.Dimension(460, 423));

        jTableSinhVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8"
            }
        ));
        jScrollPane1.setViewportView(jTableSinhVien);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nhập thông tin tìm kiếm sinh viên", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

        jLabel1.setText("Từ khóa:");

        jLabel4.setText("Chuyên khoa:");

        cboChuyenKhoa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TenKhoa" }));

        btnTimKiem.setText("Tìm kiếm");
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTuKhoa, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cboChuyenKhoa, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(btnTimKiem)
                .addContainerGap(51, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtTuKhoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(cboChuyenKhoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTimKiem))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnLuu.setText("Lưu");
        btnLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuActionPerformed(evt);
            }
        });

        btnDong.setText("Đóng");
        btnDong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDongActionPerformed(evt);
            }
        });

        btnThemMoi.setText("Thêm mới");
        btnThemMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemMoiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(btnThemMoi)
                .addGap(18, 18, 18)
                .addComponent(btnSua)
                .addGap(18, 18, 18)
                .addComponent(btnXoa)
                .addGap(18, 18, 18)
                .addComponent(btnLuu)
                .addGap(18, 18, 18)
                .addComponent(btnDong)
                .addGap(16, 16, 16))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSua)
                    .addComponent(btnXoa)
                    .addComponent(btnLuu)
                    .addComponent(btnDong)
                    .addComponent(btnThemMoi))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 854, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        //Gọi hàm hiển thị danh sách sinh viên
	hienThiDanhSachSinhVien();
    }//GEN-LAST:event_btnTimKiemActionPerformed

    private void btnLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuActionPerformed

    }//GEN-LAST:event_btnLuuActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
       
        //Ngăn không cho người dùng sửa thông tin khi double click vào jTable
        jTableSinhVien.setDefaultEditor(Object.class, null); 	

        //Gọi hàm hiển thị danh sách khoa
	hienThiDanhSachKhoa();
	
	//Gọi hàm hiển thị danh sách sinh viên
	hienThiDanhSachSinhVien();
    }//GEN-LAST:event_formWindowOpened

    private void btnDongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDongActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnDongActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        //Khai báo dòng cần chọn
	int dong = 0;
	
	//Khai báo mã sinh viên cần sửa
	String maSV = "";
	
	//Chọn dòng trên table
	dong = jTableSinhVien.getSelectedRow();
 
	if(dong != -1)
	{
	    //Lấy mã sinh viên từ dòng được chọn
	    maSV = "" + jTableSinhVien.getValueAt(dong, 0);	
	}
	else
	{
	    JOptionPane.showMessageDialog(rootPane, "Bạn phải chọn sinh viên cần sửa thông tin");
	    return;	    
	}
	
	//Khai báo object để hiển thị form sửa thông tin sinh viên
	fmRevDanhSachSV fmSua = new fmRevDanhSachSV();
	
	//Truyền giá trị mã sinh viên vào form sửa
	fmSua.setMaSV(maSV);
	
	//Hiển thị form sửa thông tin sinh viên
	fmSua.setVisible(true);
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
	//Khai báo dòng cần chọn
	int dong = 0;

	//Khai báo mã sinh viên cần xóa
	String maSV = "";

	//Chọn dòng trên table
	dong = jTableSinhVien.getSelectedRow();
	
	//Bắt lỗi khi chưa chọn sinh viên cần xóa
	if(dong != -1)
	{
	    //Lấy mã sinh viên từ dòng được chọn
	    maSV = "" + jTableSinhVien.getValueAt(dong, 0);
	    
	    //Khai báo object để gọi hàm xóa thông tin sinh viên
	    SinhVienBus sinhVienBus = new SinhVienBus();
	    
	    //Đưa ra cảnh báo trước khi xóa
	    int ketQua = JOptionPane.showConfirmDialog(rootPane, "Bạn có chắc chắn muốn xóa không ?", "Cảnh báo", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
	
	    //Thực hiện xóa
	    if(ketQua == JOptionPane.YES_OPTION)
	    {
		//Gọi hàm xóa thông tin sinh viên
		boolean xoa = sinhVienBus.xoaSV(maSV);
		
		//Xóa thành công
		if(xoa)
		{
		    hienThiDanhSachSinhVien();
		}
                else
                {
                    JOptionPane.showMessageDialog(rootPane, "Không thể xóa thông tin sinh viên đã được sử dụng. Vui lòng thử lại", "Warning", JOptionPane.ERROR_MESSAGE);                    
                }
	    }
	}
	else
	{
	    JOptionPane.showMessageDialog(rootPane, "Bạn phải chọn sinh viên cần xóa thông tin");	    
	}
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnThemMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemMoiActionPerformed
	//Khai báo object để hiển thị form thêm mới thông tin sinh viên
	fmRevDanhSachSV fmThemMoi = new fmRevDanhSachSV();
	
	//Hiển thị form thêm mới thông tin sinh viên
	fmThemMoi.setVisible(true);
    }//GEN-LAST:event_btnThemMoiActionPerformed

    public void hienThiDanhSachKhoa()
    {
	//Khai báo object
	ChuyenKhoaBus chuyenKhoaBus = new ChuyenKhoaBus();
	
	//Gọi hàm lấy danh sách khoa
	List<ChuyenKhoa> lstKhoa = chuyenKhoaBus.layDanhSachKhoa();
	
	//Set mục khoa đầu trống để hiển thị toàn bộ danh sách sinh viên
        ChuyenKhoa root = new ChuyenKhoa();
        root.setMaKhoa("");
        root.setTenKhoa("---Chọn khoa---");
        lstKhoa.add(0, root);
	
	//Khai báo model để hiển thị lên combobox
	DefaultComboBoxModel model = new DefaultComboBoxModel();
	
	//Gán object vào model
	for(ChuyenKhoa objKhoa: lstKhoa)
	{
	    model.addElement(objKhoa);         
	}
       
	//Render để hiển thị tên khoa trên combobox
	cboChuyenKhoa.setRenderer(new ChuyenKhoaRender());
	
	//Set model lên combobox
	cboChuyenKhoa.setModel(model);
    }    
    
    /**
     * Hàm hiển thị danh sách tìm kiếm sinh viên
     */
    public static void hienThiDanhSachSinhVien()
    {
	//Khai báo từ khóa mà mã khoa cần tìm
	String tuKhoa = "", maKhoa = "";
	
	//Lấy từ khóa và mã khoa lựa chọn để tìm kiếm
	tuKhoa = txtTuKhoa.getText();
	
	ChuyenKhoa objKhoa = (ChuyenKhoa)cboChuyenKhoa.getSelectedItem();
	
        if(objKhoa != null)
        {
            maKhoa = objKhoa.getMaKhoa();
        }
	
	//Khai báo tiêu đề cho table
	String tieuDe[] = new String[]{"Mã sinh viên", "Họ Tên", "Giới tính", "Ngày sinh", "Điện thoại", "Email", "Địa chỉ", "Mã Khoa"};
	
	//Khai báo model để hiển thị dữ liệu lên table
	DefaultTableModel model = new DefaultTableModel(tieuDe, 0);
	
	//Khai báo đối tượng từ lớp SinhVienBus
	SinhVienBus sinhVienBus = new SinhVienBus();
	
	//Gọi hàm lấy danh sách sinh viên
	List<SinhVien> lstSV = sinhVienBus.timKiemSV(tuKhoa, maKhoa);
	
	//Khai báo đối tượng để format ngày sinh
	SimpleDateFormat date = new SimpleDateFormat("dd/MM/yyyy");
	
	//Khai báo đối tượng để chứa thông tin sinh viên và thêm vào model
	Object row[];	
	
	//Duyệt từng đối tượng sinh viên để thêm vào đối tượng row[]
	for(SinhVien objSV: lstSV)
	{
	    row = new Object[8];
	    //Gán giá trị cho đối tượng
	    row[0] = objSV.getMaSV();
	    row[1] = objSV.getHoTen();
	    if(objSV.getGioiTinh() == 1)
	    {
		row[2] = "Nữ";
	    }
	    else
	    {
		row[2] = "Nam";
	    }
	    if(objSV.getNgaySinh() != null)
	    {
		row[3] = date.format(objSV.getNgaySinh());
	    }
	    row[4] = objSV.getDienThoai();
	    row[5] = objSV.getEmail();
	    row[6] = objSV.getDiaChi();
	    row[7] = objSV.getMaKhoa();
	    
	    //Thêm đối tượng vào model
	    model.addRow(row);
	    
	}
		
	//Thêm model vào table
	jTableSinhVien.setModel(model);	
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
	/* Set the Nimbus look and feel */
	//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
	/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
	 */
	try {
	    for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
		if ("Nimbus".equals(info.getName())) {
		    javax.swing.UIManager.setLookAndFeel(info.getClassName());
		    break;
		}
	    }
	} catch (ClassNotFoundException ex) {
	    java.util.logging.Logger.getLogger(fmDanhSachSV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (InstantiationException ex) {
	    java.util.logging.Logger.getLogger(fmDanhSachSV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (IllegalAccessException ex) {
	    java.util.logging.Logger.getLogger(fmDanhSachSV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (javax.swing.UnsupportedLookAndFeelException ex) {
	    java.util.logging.Logger.getLogger(fmDanhSachSV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	}
	//</editor-fold>

	/* Create and display the form */
	java.awt.EventQueue.invokeLater(new Runnable() {
	    public void run() {
		new fmDanhSachSV().setVisible(true);
	    }
	});
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDong;
    private javax.swing.JButton btnLuu;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThemMoi;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton btnXoa;
    private static javax.swing.JComboBox<String> cboChuyenKhoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private static javax.swing.JTable jTableSinhVien;
    private javax.swing.JTextField jTextField6;
    private static javax.swing.JTextField txtTuKhoa;
    // End of variables declaration//GEN-END:variables
}
