/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package project_qlsinhvien;

import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author ADMIN
 */
public class fmRevNguoiDung extends javax.swing.JFrame {

    private String tenDangNhap = "";

    public String getTenDangNhap() {
        return tenDangNhap;
    }

    public void setTenDangNhap(String tenDangNhap) {
        this.tenDangNhap = tenDangNhap;
    }
    
    /**
     * Creates new form fmThemNguoiDung
     */
    public fmRevNguoiDung() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtTenDangNhap = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtHoTen = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btnCapNhat = new javax.swing.JButton();
        btnDong = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        cboVaiTro = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        txtDienThoai = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtMatKhau = new javax.swing.JPasswordField();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nhập thông tin người dùng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

        jLabel1.setText("Tên đăng nhập (*):");

        jLabel2.setText("Mật khẩu (*):");

        jLabel4.setText("Họ tên (*):");

        jLabel5.setText("Điện thoại (*):");

        btnCapNhat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_qlsinhvien/images/icons8-update-16.png"))); // NOI18N
        btnCapNhat.setText("Cập nhật");
        btnCapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhatActionPerformed(evt);
            }
        });

        btnDong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_qlsinhvien/images/icons8-close-window-16.png"))); // NOI18N
        btnDong.setText("Đóng");
        btnDong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDongActionPerformed(evt);
            }
        });

        jLabel8.setText("Vai trò:");

        cboVaiTro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TenVaiTro" }));

        jLabel9.setText("Email:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCapNhat)
                        .addGap(18, 18, 18)
                        .addComponent(btnDong, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEmail)
                            .addComponent(cboVaiTro, 0, 318, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtDienThoai, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtTenDangNhap, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE)
                                    .addComponent(txtHoTen)
                                    .addComponent(txtMatKhau))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(22, 22, 22))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtTenDangNhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtDienThoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboVaiTro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCapNhat)
                    .addComponent(btnDong))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCapNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhatActionPerformed
        //Khai báo biến
        String tenDangNhap = "", matKhau = "", matKhauMH = "", hoTen = "", dienThoai = "", email = "", maVaiTro = "";
        
        //Lấy thông tin trên giao diện
        tenDangNhap = txtTenDangNhap.getText().trim();
        matKhau = new String(txtMatKhau.getPassword());
        hoTen = txtHoTen.getText().trim();
        dienThoai = txtDienThoai.getText().trim();
        email = txtEmail.getText().trim();
        
        VaiTro objVaiTro = (VaiTro)cboVaiTro.getSelectedItem();
        
        if(objVaiTro != null)
        {
            maVaiTro = objVaiTro.getMaVaiTro().trim();
        }
        
	//Bắt lỗi khi người dùng không nhập đủ thông tin 	
	//Tên đăng nhập        
	if(tenDangNhap.length() == 0)
	{
            JOptionPane.showMessageDialog(rootPane, "Bạn cần nhập tên đăng nhập");
            txtTenDangNhap.requestFocus();
            return;	    
	}
	//Mật khẩu        
	if(matKhau.length() == 0)
	{
            JOptionPane.showMessageDialog(rootPane, "Bạn cần nhập mật khẩu");
            jPanel1.requestFocus();
            return;	    
	} 
	//Họ tên 
	if(hoTen.length() == 0)
	{
            JOptionPane.showMessageDialog(rootPane, "Bạn cần nhập họ tên");
            txtHoTen.requestFocus();
            return;	    
	}
	//Kiểm tra họ tên nếu chứa chữ số
	char hoTenCheck[] = hoTen.toCharArray();
	
	for(char giaTri: hoTenCheck)
	{
	    if(Character.isDigit(giaTri))
	    {
		JOptionPane.showMessageDialog(rootPane, "Tên không hợp lệ");
		txtHoTen.requestFocus();
		return;
	    }	    
	}
	//Điện thoại
	if(dienThoai.length() == 0)
	{
            JOptionPane.showMessageDialog(rootPane, "Bạn cần nhập số điện thoại sinh viên");
            txtDienThoai.requestFocus();
            return;	    
	}
	if(dienThoai.contains(" "))
	{
	    JOptionPane.showMessageDialog(rootPane, "Số điện thoại không hợp lệ");
	    txtDienThoai.requestFocus();
	    return;	    
	}
	//Kiểm tra nếu điện thoại chứa kí tự chữ cái
	char dienThoaiCheck[] = dienThoai.toCharArray();
	
	for(char giaTri: dienThoaiCheck)
	{
	    if(Character.isLetter(giaTri))
	    {
		JOptionPane.showMessageDialog(rootPane, "Số điện thoại không hợp lệ");
		txtDienThoai.requestFocus();
		return;
	    }	    
	}
        
	//Khai báo đối tượng để gọi hàm cập nhật/thêm mới
	NguoiDungBus nguoiDungBus = new NguoiDungBus(); 
        
        //Mã hóa mật khẩu
        matKhauMH = nguoiDungBus.GenerateMD5(matKhau);

        //Khai báo đối tượng
        NguoiDung objUser = new NguoiDung();
        
        //Gán giá trị cho object
        objUser.setTenDangNhap(tenDangNhap);
        objUser.setMatKhau(matKhauMH);
        objUser.setHoTen(hoTen);
        objUser.setDienThoai(dienThoai);
        objUser.setEmail(email);
        if(objVaiTro != null)
        {
            objUser.setMaVaiTro(maVaiTro);
        }
	
	//Khai báo kết quả trả về và kiểm tra trùng mã sinh viên
	boolean ketQua, kiemTraTrung; 
	
	//Gọi hàm kiểm tra trùng mã sinh viên
	kiemTraTrung = nguoiDungBus.kiemTraTrungTenDN(tenDangNhap);
	
	if(!this.tenDangNhap.isEmpty())//TH sửa
	{
	    ketQua = nguoiDungBus.capNhatUser(objUser);
            if(ketQua)
            {
                JOptionPane.showMessageDialog(rootPane, "Cập nhật thông tin người dùng thành công");
            }            	    
	}
	else//TH thêm mới
	{
	    if(kiemTraTrung == true)//Nếu không trùng tên đăng nhập
	    {
		ketQua = nguoiDungBus.themMoiUser(objUser);
                if(ketQua)
                {
                    JOptionPane.showMessageDialog(rootPane, "Thêm mới thông tin người dùng thành công");	
                }                  		
	    }
	    else
	    {
		JOptionPane.showMessageDialog(rootPane, "Tên đăng nhập này đã tồn tại. Vui lòng nhập lại tên đăng nhập");
		txtTenDangNhap.requestFocus();
		return;		
	    }
	}
	
	if(ketQua)
	{
            fmDSNguoiDung.hienThiDanhSachUser();
	}        
        
    }//GEN-LAST:event_btnCapNhatActionPerformed

    private void btnDongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDongActionPerformed
        //Đóng cửa sổ hiện thời
        this.setVisible(false);
    }//GEN-LAST:event_btnDongActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
     	//Gọi hàm hiển thị chi tiết vai trò
	hienThiDanhSachVaiTro();
	
	//Gọi hàm sửa/thêm mới thông tin sinh viên
	if(!tenDangNhap.isEmpty())
	{
	    this.setTitle("Sửa thông tin người dùng");
	    //Gọi hàm hiển thị chi tiết người dùng
            hienThiChiTietNguoiDung();
	    
	}
	else
	{
	    this.setTitle("Thêm mới thông tin người dùng");
	}
    }//GEN-LAST:event_formWindowOpened

    public void hienThiChiTietNguoiDung()
    {
	//Khai báo đối tượng 
	NguoiDungBus nguoiDungBus = new NguoiDungBus();
	
	//Gọi hàm hiển thị chi tiết
	NguoiDung objUser = nguoiDungBus.layChiTietUser(tenDangNhap);
	
	//Gán giá trị vào textfield
	if(objUser != null)
	{
            txtTenDangNhap.setText(tenDangNhap);
            txtTenDangNhap.setEditable(false);
            txtMatKhau.setText(objUser.getMatKhau());
	    txtHoTen.setText(objUser.getHoTen());
	    txtDienThoai.setText(objUser.getDienThoai());
	    txtEmail.setText(objUser.getEmail());
	    
            VaiTroBus vaiTroBus = new VaiTroBus();

            VaiTro objVaiTro = vaiTroBus.layChiTietVaiTroUser(objUser.getMaVaiTro());
	    
	    if(objVaiTro != null)
	    {
		//Hiển thị khoa của sinh viên được chọn trên combobox
		cboVaiTro.getModel().setSelectedItem(objVaiTro);		
	    }
	}
    } 
    
    /**
     * Hiển thị danh sách vai trò người dùng trên cbo
     */
    public void hienThiDanhSachVaiTro()
    {
	//Khai báo object
	VaiTroBus vaiTroBus = new VaiTroBus();
	
	//Gọi hàm lấy danh sách khoa
	List<VaiTro> lstVaiTro = vaiTroBus.layDanhSachVaiTro();
	
	//Khai báo model để hiển thị lên combobox
	DefaultComboBoxModel model = new DefaultComboBoxModel();
	
	//Gán object vào model
	for(VaiTro objVaiTro: lstVaiTro)
	{
	    model.addElement(objVaiTro);         
	}
       
	//Render để hiển thị tên khoa trên combobox
	cboVaiTro.setRenderer(new VaiTroRender());
	
	//Set model lên combobox
	cboVaiTro.setModel(model);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fmRevNguoiDung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fmRevNguoiDung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fmRevNguoiDung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fmRevNguoiDung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fmRevNguoiDung().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCapNhat;
    private javax.swing.JButton btnDong;
    private javax.swing.JComboBox<String> cboVaiTro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtDienThoai;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtHoTen;
    private javax.swing.JPasswordField txtMatKhau;
    private javax.swing.JTextField txtTenDangNhap;
    // End of variables declaration//GEN-END:variables
}
