/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package namcat_baithuchanh_150624;

import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author ADMIN
 */
public class fmThiSinhRev extends javax.swing.JFrame {

    private String soBaoDanh = "";
      
    public String getSoBaoDanh() {
	return soBaoDanh;
    }

    public void setSoBaoDanh(String soBaoDanh) {
	this.soBaoDanh = soBaoDanh;
    }
    
    /**
     * Creates new form fmThiSinhRev
     */
    public fmThiSinhRev() {
	initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cboGioiTinh = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtDiemToan = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtDiaChi = new javax.swing.JTextField();
        txtNgaySinh = new javax.swing.JTextField();
        txtHoTen = new javax.swing.JTextField();
        txtSoBaoDanh = new javax.swing.JTextField();
        btnCapNhat = new javax.swing.JButton();
        btnDong = new javax.swing.JButton();
        txtDiemLy = new javax.swing.JTextField();
        txtDiemHoa = new javax.swing.JTextField();

        jLabel4.setText("jLabel4");

        jTextField1.setText("jTextField1");

        jTextField6.setText("jTextField6");

        jButton2.setText("jButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nhập thông tin thí sinh", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

        jLabel1.setText("Số báo danh:");

        jLabel2.setText("Họ tên:");

        jLabel3.setText("Giới tính: ");

        jLabel5.setText("Ngày sinh:");

        jLabel6.setText("Địa chỉ:");

        cboGioiTinh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nam", "Nữ" }));

        jLabel7.setText("Điểm thi:");

        jLabel9.setText("Toán:");

        jLabel10.setText("Lý:");

        jLabel11.setText("Hóa:");

        btnCapNhat.setText("Cập nhật");
        btnCapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhatActionPerformed(evt);
            }
        });

        btnDong.setText("Đóng");
        btnDong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDongActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtHoTen)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cboGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(txtNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtDiaChi, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtSoBaoDanh)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnCapNhat)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(18, 18, 18)
                                .addComponent(txtDiemToan, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(15, 15, 15)
                                .addComponent(jLabel10)
                                .addGap(18, 18, 18)
                                .addComponent(txtDiemLy, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel11)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(txtDiemHoa, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addComponent(btnDong)))))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtSoBaoDanh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cboGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel9)
                    .addComponent(txtDiemToan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(txtDiemLy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDiemHoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDong)
                    .addComponent(btnCapNhat))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
	if(!soBaoDanh.isEmpty())
	{
	    hienThiChiTietThiSinh();
	    this.setTitle("Sửa thông tin thí sinh");
	}
	else
	{
	    txtSoBaoDanh.setText("TLA");
	    this.setTitle("Thêm mới thông tin thí sinh");
	}		
    }//GEN-LAST:event_formWindowOpened

    private void btnDongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDongActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_btnDongActionPerformed

    private void btnCapNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhatActionPerformed
	
	//Khai báo các biến để thêm/cập nhật thông tin trên table
	String strSoBaoDanh = "", strHoTen = "", strNgaySinh = "", strQueQuan = "", strGioiTinh = "";
	String strDiemToan = "", strDiemLy = "", strDiemHoa = "";
	double diemToan = 0, diemLy = 0, diemHoa = 0, tongDiem = 0;
	
	//Lấy thông tin người dùng nhập từ bàn phím
	strSoBaoDanh = txtSoBaoDanh.getText().trim();
	strHoTen = txtHoTen.getText().trim();
	strNgaySinh = txtNgaySinh.getText().trim();
	strQueQuan = txtDiaChi.getText().trim();
	strGioiTinh = "" + cboGioiTinh.getSelectedIndex();
	strDiemToan = txtDiemToan.getText().trim();
	strDiemLy = txtDiemLy.getText().trim();
	strDiemHoa = txtDiemHoa.getText().trim();
	
	//Bắt lỗi người dùng khi chưa nhập đầy đủ thông tin
	if(strSoBaoDanh.length() == 0)
	{
	    JOptionPane.showMessageDialog(rootPane, "Bạn phải nhập số báo danh thí sinh");
	    txtSoBaoDanh.requestFocus();
	    return;	    
	}
	
	if(strHoTen.length() == 0)
	{
	    JOptionPane.showMessageDialog(rootPane, "Bạn phải họ tên thí sinh");
	    txtHoTen.requestFocus();
	    return;	    
	}

	if(strDiemToan.length() == 0 || strDiemLy.length() == 0 || strDiemHoa.length() == 0)
	{
	    JOptionPane.showMessageDialog(rootPane, "Bạn phải đầy đủ điểm số thí sinh");
	    return;	    
	}	
	
	try {
	    diemToan = Double.parseDouble(strDiemToan);
	    diemLy = Double.parseDouble(strDiemLy);
	    diemHoa = Double.parseDouble(strDiemHoa);	    
	    tongDiem = diemToan + diemLy + diemHoa;	
	} catch (NumberFormatException ex) {
	    System.err.println("Có lỗi khi nhập. Chi tiết lỗi: " + ex.getMessage());
	    JOptionPane.showMessageDialog(rootPane, "Bạn phải nhập giá trị điểm là kiểu số");
	    return;
	}

        //Khai báo đối tượng để add thông tin thí sinh
	ThiSinh objTS = new ThiSinh();
	
	//Gán giá trị cho đối tượng
	objTS.setSoBaoDanh(strSoBaoDanh);
	objTS.setHoTen(strHoTen);
	objTS.setNgaySinh(strNgaySinh);
	objTS.setQueQuan(strQueQuan);
	objTS.setGioiTinh("" + strGioiTinh);
	objTS.setTongDiem(tongDiem);
	objTS.setDiemToan(diemToan);
	objTS.setDiemLy(diemLy);
	objTS.setDiemHoa(diemHoa);
	
	//Kiểm tra trùng số báo danh
	boolean kiemTraTrung = DataProvider.getThiSinhBus().kiemTraTrungSoBD(strSoBaoDanh);
	
	//Gán đối tượng sinh viên thêm mới vào list
	if(!soBaoDanh.isEmpty())
	{
	    List<ThiSinh> lstTS = DataProvider.getThiSinhBus().sua(objTS);
	    JOptionPane.showMessageDialog(rootPane, "Cập nhật thông tin thí sinh thành công");
	}
	else
	{
	    if(kiemTraTrung == true)
	    {
		List<ThiSinh> lstTS = DataProvider.getThiSinhBus().themMoi(objTS);
		JOptionPane.showMessageDialog(rootPane, "Thêm mới thông tin thí sinh thành công");
	    }
	    else
	    {
		JOptionPane.showMessageDialog(rootPane, "Số báo danh này đã tồn tại. Vui lòng nhập lại số báo danh");
		txtSoBaoDanh.requestFocus();
		return;
	    }
	}

	//Reload lại danh sách thí sinh
	fmDanhSachThiSinh.hienThiDanhSachThiSinh();
    }//GEN-LAST:event_btnCapNhatActionPerformed

    public void hienThiChiTietThiSinh()
    {
	//Khai báo đối tượng để lấy thông tin thí sinh cần xem
	ThiSinh objTS = DataProvider.getThiSinhBus().layChiTiet(soBaoDanh);
	
	//Hiển thị đối tượng lên giao diện
	if(objTS != null)
	{
	    txtSoBaoDanh.setText(objTS.getSoBaoDanh());
	    txtHoTen.setText(objTS.getHoTen());
	    if(objTS.getGioiTinh().equals("0"))
	    {
		cboGioiTinh.setSelectedIndex(0);
	    }
	    else
	    {
		cboGioiTinh.setSelectedIndex(1);
	    }
	    txtNgaySinh.setText(objTS.getNgaySinh());
	    txtDiaChi.setText(objTS.getQueQuan());
	    txtDiemToan.setText("" + objTS.getDiemToan());
	    txtDiemLy.setText("" + objTS.getDiemLy());
	    txtDiemHoa.setText("" + objTS.getDiemHoa());	
	}	    
    }

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
	/* Set the Nimbus look and feel */
	//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
	/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
	 */
	try {
	    for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
		if ("Nimbus".equals(info.getName())) {
		    javax.swing.UIManager.setLookAndFeel(info.getClassName());
		    break;
		}
	    }
	} catch (ClassNotFoundException ex) {
	    java.util.logging.Logger.getLogger(fmThiSinhRev.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (InstantiationException ex) {
	    java.util.logging.Logger.getLogger(fmThiSinhRev.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (IllegalAccessException ex) {
	    java.util.logging.Logger.getLogger(fmThiSinhRev.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (javax.swing.UnsupportedLookAndFeelException ex) {
	    java.util.logging.Logger.getLogger(fmThiSinhRev.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	}
	//</editor-fold>

	/* Create and display the form */
	java.awt.EventQueue.invokeLater(new Runnable() {
	    public void run() {
		new fmThiSinhRev().setVisible(true);
	    }
	});
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCapNhat;
    private javax.swing.JButton btnDong;
    private javax.swing.JComboBox<String> cboGioiTinh;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField txtDiaChi;
    private javax.swing.JTextField txtDiemHoa;
    private javax.swing.JTextField txtDiemLy;
    private javax.swing.JTextField txtDiemToan;
    private javax.swing.JTextField txtHoTen;
    private javax.swing.JTextField txtNgaySinh;
    private javax.swing.JTextField txtSoBaoDanh;
    // End of variables declaration//GEN-END:variables
}
