/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package namcat_baitaplaptrinhdesktopjv01part3;

import java.util.Arrays;
import java.util.Scanner;
import javax.swing.JOptionPane;

/**
 *
 * @author Dell Precision 7550
 */
public class fmTangDanGiamDan extends javax.swing.JFrame {

    /**
     * Creates new form fmTangDanGiamDan
     */
    public fmTangDanGiamDan() {
	initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtGiaTri = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtGiamDan = new javax.swing.JTextField();
        btnSapXep = new javax.swing.JButton();
        txtTangDan = new javax.swing.JTextField();
        txtGiaTri1 = new javax.swing.JTextField();
        txtGiaTri2 = new javax.swing.JTextField();
        txtGiaTri3 = new javax.swing.JTextField();
        txtGiaTri4 = new javax.swing.JTextField();
        txtGiaTri5 = new javax.swing.JTextField();
        txtGiaTri6 = new javax.swing.JTextField();
        txtGiaTri7 = new javax.swing.JTextField();
        txtGiaTri8 = new javax.swing.JTextField();
        txtGiaTri9 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Chương trình sắp xếp thứ tự", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

        jLabel1.setText("Giá trị cần sắp xếp:");

        txtGiaTri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGiaTriActionPerformed(evt);
            }
        });

        jLabel2.setText("Thứ tự tăng dần:");

        jLabel3.setText("Thứ tự giảm dần:");

        txtGiamDan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGiamDanActionPerformed(evt);
            }
        });

        btnSapXep.setText("Sắp xếp");
        btnSapXep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSapXepActionPerformed(evt);
            }
        });

        txtTangDan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTangDanActionPerformed(evt);
            }
        });

        txtGiaTri1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGiaTri1ActionPerformed(evt);
            }
        });

        txtGiaTri2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGiaTri2ActionPerformed(evt);
            }
        });

        txtGiaTri3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGiaTri3ActionPerformed(evt);
            }
        });

        txtGiaTri4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGiaTri4ActionPerformed(evt);
            }
        });

        txtGiaTri5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGiaTri5ActionPerformed(evt);
            }
        });

        txtGiaTri6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGiaTri6ActionPerformed(evt);
            }
        });

        txtGiaTri7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGiaTri7ActionPerformed(evt);
            }
        });

        txtGiaTri8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGiaTri8ActionPerformed(evt);
            }
        });

        txtGiaTri9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGiaTri9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnSapXep)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txtGiaTri, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtGiaTri1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtGiaTri2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtGiaTri3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtGiaTri4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtGiaTri5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtGiaTri6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtGiaTri7, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtGiaTri8, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtGiaTri9, javax.swing.GroupLayout.PREFERRED_SIZE, 35, Short.MAX_VALUE))
                            .addComponent(txtTangDan)
                            .addComponent(txtGiamDan))))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtGiaTri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtGiaTri1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtGiaTri2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtGiaTri3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtGiaTri4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtGiaTri5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtGiaTri6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtGiaTri7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtGiaTri8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtGiaTri9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtTangDan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtGiamDan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnSapXep)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(14, 14, 14))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSapXepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSapXepActionPerformed
        // TODO add your handling code here:
	Scanner sc = new Scanner(System.in);
	
        //Declare variables
        String strGiaTri = "", strGiaTri1 = "", strGiaTri2 = "", strGiaTri3 = "", strGiaTri4 = "", strGiaTri5 = "", strGiaTri6 = "", strGiaTri7 = "", strGiaTri8 = "", strGiaTri9 = "", strTangDan = "", strGiamDan = "";
	int giaTri = 0, giaTri1 = 0, giaTri2 = 0, giaTri3 = 0, giaTri4 = 0, giaTri5 = 0, giaTri6 = 0, giaTri7 = 0, giaTri8 = 0, giaTri9 = 0,temp = 0;
	
	//Take user information entered from the keyboard	
	strGiaTri = txtGiaTri.getText();
	strGiaTri1 = txtGiaTri1.getText();
	strGiaTri2 = txtGiaTri2.getText();
	strGiaTri3 = txtGiaTri3.getText();
	strGiaTri4 = txtGiaTri4.getText();
	strGiaTri5 = txtGiaTri5.getText();
	strGiaTri6 = txtGiaTri6.getText();
	strGiaTri7 = txtGiaTri7.getText();
	strGiaTri8 = txtGiaTri8.getText();
	strGiaTri9 = txtGiaTri9.getText();
	
	//Use Try_Catch to catch the error
	try
	{
	    giaTri = Integer.parseInt(strGiaTri);
	    giaTri1 = Integer.parseInt(strGiaTri1);
	    giaTri2 = Integer.parseInt(strGiaTri2);
	    giaTri3 = Integer.parseInt(strGiaTri3);
	    giaTri4 = Integer.parseInt(strGiaTri4);
	    giaTri5 = Integer.parseInt(strGiaTri5);
	    giaTri6 = Integer.parseInt(strGiaTri6);
	    giaTri7 = Integer.parseInt(strGiaTri7);
	    giaTri8 = Integer.parseInt(strGiaTri8);
	    giaTri9 = Integer.parseInt(strGiaTri9);
	}
	catch(NumberFormatException ex)
	{
	    System.out.println("Bạn phải nhập đầy đủ các ô giá trị theo kiểu số nguyên. Chi tiết lỗi: " + ex.getMessage());
	    JOptionPane.showMessageDialog(rootPane, "Bạn phải nhập đầy đủ các ô giá trị theo kiểu số nguyên");
	    return;
	}

	//Enter the value to array
	int arr[] = new int[10];
	
	arr[0] = giaTri;
	arr[1] = giaTri1;
	arr[2] = giaTri2;
	arr[3] = giaTri3;
	arr[4] = giaTri4;
	arr[5] = giaTri5;
	arr[6] = giaTri6;
	arr[7] = giaTri7;
	arr[8] = giaTri8;
	arr[9] = giaTri9;
	
	//Use loop to sort the array in ascending, descending order
	for (int i = 0; i < arr.length - 1; i++) {
	    for (int j = i + 1; j < arr.length; j++) {
		if (arr[i] > arr[j]) {
		    temp = arr[j];
		    arr[j] = arr[i];
		    arr[i] = temp;
		}
	    }
	}
	
	for(int i = 0; i < arr.length; i++)
	{
	    strTangDan += arr[i] + "-";
	}
	
	for (int i = 0; i < arr.length - 1; i++) {
	    for (int j = i + 1; j < arr.length; j++) {
		if (arr[i] < arr[j]) {
		    temp = arr[j];
		    arr[j] = arr[i];
		    arr[i] = temp;
		}
	    }
	}
	
	for(int i = 0; i < arr.length; i++)
	{
	    strGiamDan += arr[i] + "-";
	}
	
	//Print results
	txtTangDan.setText(strTangDan.substring(0, strTangDan.length()-1));
	txtGiamDan.setText(strGiamDan.substring(0, strGiamDan.length()-1));
	
    }//GEN-LAST:event_btnSapXepActionPerformed

    private void txtGiamDanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGiamDanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGiamDanActionPerformed

    private void txtGiaTriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGiaTriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGiaTriActionPerformed

    private void txtTangDanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTangDanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTangDanActionPerformed

    private void txtGiaTri1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGiaTri1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGiaTri1ActionPerformed

    private void txtGiaTri2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGiaTri2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGiaTri2ActionPerformed

    private void txtGiaTri3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGiaTri3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGiaTri3ActionPerformed

    private void txtGiaTri4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGiaTri4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGiaTri4ActionPerformed

    private void txtGiaTri5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGiaTri5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGiaTri5ActionPerformed

    private void txtGiaTri6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGiaTri6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGiaTri6ActionPerformed

    private void txtGiaTri7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGiaTri7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGiaTri7ActionPerformed

    private void txtGiaTri8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGiaTri8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGiaTri8ActionPerformed

    private void txtGiaTri9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGiaTri9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGiaTri9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
	/* Set the Nimbus look and feel */
	//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
	/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
	 */
	try {
	    for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
		if ("Nimbus".equals(info.getName())) {
		    javax.swing.UIManager.setLookAndFeel(info.getClassName());
		    break;
		}
	    }
	} catch (ClassNotFoundException ex) {
	    java.util.logging.Logger.getLogger(fmTangDanGiamDan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (InstantiationException ex) {
	    java.util.logging.Logger.getLogger(fmTangDanGiamDan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (IllegalAccessException ex) {
	    java.util.logging.Logger.getLogger(fmTangDanGiamDan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (javax.swing.UnsupportedLookAndFeelException ex) {
	    java.util.logging.Logger.getLogger(fmTangDanGiamDan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	}
	//</editor-fold>

	/* Create and display the form */
	java.awt.EventQueue.invokeLater(new Runnable() {
	    public void run() {
		new fmTangDanGiamDan().setVisible(true);
	    }
	});
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSapXep;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtGiaTri;
    private javax.swing.JTextField txtGiaTri1;
    private javax.swing.JTextField txtGiaTri2;
    private javax.swing.JTextField txtGiaTri3;
    private javax.swing.JTextField txtGiaTri4;
    private javax.swing.JTextField txtGiaTri5;
    private javax.swing.JTextField txtGiaTri6;
    private javax.swing.JTextField txtGiaTri7;
    private javax.swing.JTextField txtGiaTri8;
    private javax.swing.JTextField txtGiaTri9;
    private javax.swing.JTextField txtGiamDan;
    private javax.swing.JTextField txtTangDan;
    // End of variables declaration//GEN-END:variables
}
